### ISSUE TITLE
rename plugin for consistency

### ISSUE THREAD

**Issue by noerw** [nilsnolde/OSMtools#42]
While you're refactoring for QGIS3;
afaik QGIS3 will use a separate plugin repository. You might use the opportunity to rename the plugin from "OSM Tools" to "ORS Tools"? I had trouble finding the plugin the first time..

**Comment by nilsnolde** [comment]
Yes, they have to use separate repos for dependency conflicts.

It originally was ORS Tools. Then I changed it to OSM Tools for the idea to offer many more API's, Graphhopper, Here, route360 etc. But for many reasons, I might not do that after all. So yeah, ORS Tools it'll probably be.

**Comment by nilsnolde** [comment]
QGIS3 will use the same plugin repo apparently. So I changed the the repo URL.
