### ISSUE TITLE
QGIS python error

### ISSUE THREAD

**Issue by geobilab** [nilsnolde/OSMtools#43]
I'm using the tool via QGIS, and I'm getting this error. any insights on this? thx
Traceback (most recent call last):
			  File "C:/-----/.qgis2/python/plugins\OSMtools\osm_tools.py", line 262, in run
			    self.access_anal.iterAnalysis()
			  File "C:/----/.qgis2/python/plugins\OSMtools\osm_tools_access.py", line 382, in iterAnalysis
			    feat_list, isochrone_list = self.accRequest(feat_in_list)
			TypeError: 'NoneType' object is not iterable

**Comment by nilsnolde** [comment]
The plugin has been deprecated for QGIS v2.x. I'm currently refactoring to QGIS v3, which will be released next week and it will catch errors like yours. So no more support for v2.x for now, sorry... But your error usually means that you had an invalid request, e.g. bad coordinates or so. There should've have been a QGIS message bar error (red bar on top of the window) detailing on the HTTP error you received.

Stay tuned for v3 release.

**Comment by geobilab** [comment]
Hi Nils. First of all, thank you for the work. I'm using QGIS 2.18.16 'Las Palmas' - this is the last release. Looking forward to test/use that plugin. Best.
