### ISSUE TITLE
empty toolbar

### ISSUE THREAD

**Issue by noerw** [nilsnolde/OSMtools#49]
At least in the QGIS 2 version, an "OSMtools" toolbar is created, but the plugin button is added to the standard "plugins" toolbar.
![screenshot from 2018-03-14 11-07-53](https://user-images.githubusercontent.com/7880552/37396058-1de21ade-2778-11e8-8a23-3c92e59c46a6.png)

idk about best practices with qgis toolbars, but creating one toolbar for each plugin seems not optimal anyway, maybe consider the "web" or "plugins" toolbar?

**Comment by nilsnolde** [comment]
Ok, will have a look at it for next version.
