### ISSUE TITLE
Isochrones Ranges

### ISSUE THREAD

**Issue by sebastiandenker** [nilsnolde/OSMtools#50]
I'd like to create isochrones from point layer for foot-walking distances with less than 1 km - e.g. 600m

I get an error with 0.6 and 0,6 creates 6km isochromes, cause the comma is used as a seperator. 

How do can I do it correctly?

Thanks
Sebastian

**Comment by nilsnolde** [comment]
Yes, that's right, the input you give in that field is split by commas and mapped to int() function, which returns integers. Wasn't thinking too much about walking profiles I guess. I'll amend in the next version. If you want to change this as a hotfix, do the following:
- Locate the plugin directory on your computer (e.g. via Plugin Manager)
- in isochrones.py, change line 50 (in v3.x) from `self.access_range_input = list(map(int,self.dlg.access_range.text().split(',')))` to `self.access_range_input = list(map(float,self.dlg.access_range.text().split(',')))`
- reload plugin or restart QGIS

That should work just fine. BTW, the isochrones are currently very smooth, so likely that 600 m walking will return pretty much a convex hull. We'll change the alpha value for polygon smoothness soon, see https://github.com/GIScience/openrouteservice/issues/137.

**Comment by sebastiandenker** [comment]
Hi Nils,
thank you very much for your quick response. The change in the code works well for me!

I'm lookin forward to further developments of your plugin.

As for now, the even the smaller diameter polygones work well and are an improvement to circle buffers.

![isochrone_600m](https://user-images.githubusercontent.com/5792421/37589103-7a1f6c3a-2b64-11e8-8b2a-b10c67d3e376.JPG)


Bye
Sebastian
