### ISSUE TITLE
ORS Routing seems to result in Python Error

### ISSUE THREAD

**Issue by civil142** [nilsnolde/OSMtools#51]
I ve tried running on a number of machines with different versions of QGIS (2.18.16 and QGIS 3.0.0), but this seems to crash out. 

2018-03-16T12:09:46	1	Traceback (most recent call last):
			  File "C:/Users/Ian/.qgis2/python/plugins\OSMtools\osm_tools.py", line 144, in run
			    route.directions_calc()
			  File "C:/Users/Ian/.qgis2/python/plugins\OSMtools\directions.py", line 137, in directions_calc
			    layer_out = self._addLine(responses, values_list)
			  File "C:/Users/Ian/.qgis2/python/plugins\OSMtools\directions.py", line 183, in _addLine
			    values_list[i][0],
			IndexError: list index out of range

**Comment by nilsnolde** [comment]
Can you please see if #47 resolves your issue?

If not, I need a more thorough description how you got there: are you trying to route from files or 'Map' buttons?

**Comment by civil142** [comment]
Yes that workaroud resolved it thank you. Its a great tool.

**Comment by nilsnolde** [comment]
works with #47 workaround

**Comment by mobcdi** [comment]
Hi Nils, I have a similar issue but I have 2 layers comprising 1000 points in the source and 10 points in the destination. I get the error in "```
directions.py", line 205, in _selectInput
    layer = [layer for layer in self.iface.mapCanvas().layers() if layer.name() == layer_name][0]
IndexError: list index out of range
``` when I select the source and destination layers using the UI. 
If I select all the features in the source layer (1000) and the destination layer (8) I do get a new layer but it only contains 8 features. I had been expecting a layer with 8000 features. If I try the matrix option I get a new attribute table but 0 features
