### ISSUE TITLE
Isochrone measurement to allow the use of non-integer 

### ISSUE THREAD

**Issue by FlytPlan** [nilsnolde/OSMtools#53]
When selecting the Isochrone unit (time or distance), I’ve tried to select distance and use 0.4km to reflect a 400m walk catchment but the plugin freezes - I understand that this is because it requires integer values (i.e. at least 1 minute or 1km).  For example it would be great to be able to use 0.4km to reflect a 400m walk distance.
Thanks

**Comment by yonnov** [comment]
This worked for me (from Nils advice), 

you can try to get around this in your local plugin installation, by replacing these lines in isochrone.py:

line 55:

self.factor = 60 if self.dimension == 'time' else 1000

to

self.factor = 60 if self.dimension == 'time' else 1

I then entered a value in meters (e.g. 400)

**Comment by FlytPlan** [comment]
Thanks for that Nils – it all works fine now.

Cheers

Matt

Matthew Root
Flyt Pty Ltd
0403 677 970

**Comment by nilsnolde** [comment]
implemented in master.. now it's in meter instead of km
