### ISSUE TITLE
python no module named yaml

### ISSUE THREAD

**Issue by BrawlPups** [nilsnolde/OSMtools#57]
when installing on mint 18 I get python no module named yaml but it seems I have yaml on the system.
It's qgis 2 point someaught not 3 so is that the problem ; )

**Comment by nilsnolde** [comment]
Can you repeat? I didn't get what QGIS version you're running.

Sounds like a broken installation though. `yaml` should be in every QGIS distro (it uses its own Py interpreter, at least under Win). Try 2.18 or 3.x

**Comment by nilsnolde** [comment]
no answer..
