### ISSUE TITLE
Isohrones limit

### ISSUE THREAD

**Issue by kapprovalija** [nilsnolde/OSMtools#65]
First of all, I want to say that this is great plugin! I started using it, and it makes routing very fast and easy. 

While I was using it I encountered next error.

When I used isochrones with travel time option everything is great until time window is 60 minutes or less. But when I used more than 61 min it reported error: 400 (Parameter 'range=3660.0' is out of range. Maximum possible value is 3600.) Is this intentional limitation or error?

Thanks in advance!
Cheers!

**Comment by carlisle1** [comment]
I'm sure Nils will be along to answer this in more detail soon, but what I do know is that the limits are those of the OpenRoute service

**Comment by nilsnolde** [comment]
Yep, @carlisle1 is right. See here:
https://openrouteservice.org/ratelimits/

It will be quite some time before we can allow higher limits. Towards the end of the year, we'll be able to support continental isochrones.
