### ISSUE TITLE
Isochrones: Estimated travel speed for the different travel modes?

### ISSUE THREAD

**Issue by fatby** [nilsnolde/OSMtools#67]
Where can I look up the estimated maximum speeds for the different travel modes (foot-walking, cycling-regular etc.). 
Are they adjustable?

Cheers 
Fabian

**Comment by TimMcCauley** [comment]
@fatby check this link please https://github.com/GIScience/openrouteservice-docs

**Comment by fatby** [comment]
@TimMcCauley That's exactly what I was looking for, thank you!
