### ISSUE TITLE
New to QGIS with training in ArcGIS - errors loading plugin

### ISSUE THREAD

**Issue by squashedcannon** [nilsnolde/OSMtools#69]
Hello, I am unable to install the OSM Tools plugin. I downloaded QGIS 3 in order to be current and began tooling around with the basics. Ideally I would like to create isochrones for an upcoming camping trip within a 5 hour drive time from our point of origin. Here is what my error reads: 

"Error transferring https://plugins.qgis.org/plugins/OSMtools/version/3.1.1/download/ - server replied: Bad Gateway"

**Comment by nilsnolde** [comment]
QGIS server issues are not part of this issue tracker. Please see https://issues.qgis.org/projects/qgis/issues. The link works for me.
