### ISSUE TITLE
Snapping tolerance?

### ISSUE THREAD

**Issue by krticka** [nilsnolde/OSMtools#71]
Hi Nils,
I just processed some data to create matrix and realized that for some points are missing results. I checked points and some of them were located slightly outside the built-up areas. 
What is the snapping tolerance for points in meters? Is it possible to make such setup in plugin? 
Is there any tool where I can check suitability of input data for routing?
Thanks.

**Comment by nilsnolde** [comment]
Hi,
what does `built-up area` mean?
Generally the ORS snapping tolerance for points to route from is set to 50 km, I believe. So that shouldn't be an issue. Not sure what happens if the point falls into the sea or similar no-go areas.

And yes, there is a snapping tolerance parameter in ORS stack, but it's not possible to increase it beyond the default.

Can you give some example coordinates (from & to) which didn't produce any results, so we can have a look?

**Comment by krticka** [comment]
Hi,
I want to create matrix between 72 regional centres for specific geographic statistical analysis. 

First, I created points from selected cities (polygons) and it happened that sometimes centroids were due to polygon irregular shape located outside built-up area, in the forest, etc. 
As I have 72 x 72points and there is 2500 locations restriction (50 x 50 points) I made a copy of input layer and split up layer into 3 parts. Than I was running matrix 3 times, each time selecting one third of points for start locations. I merged results into one file. Than I created contingency table in Excel and I found that some cities are missing.

I made some editing and moved points inside cities, trying to locate them on road network. Than I ran matrix again, but with the same result.

I was thinking about the reasons and I tried to run first third of starting points on Routing. Routes showed me that only to some locations routes were calculated. This led me to question about tolerance.
For example some points located inside roundabout were not included. Data are included (KODNUM is the unique ID field). 

Thanks for the help.
[Dostupnost.zip](https://github.com/nilsnolde/OSMtools/files/2402026/Dostupnost.zip)

**Comment by nilsnolde** [comment]
Right, thanks for the details.
Unfortunately I don't have the energy to go through those shapefiles;) I need the information in a more raw format. Can you please post 2-3 exemplary routes in the format of 

| from | to |
|----------------|-------|
| 52.1385, 8.4133 | 52.9524, 9.9213 |

or similar?
That'd be most helpful!
Thanks

**Comment by nilsnolde** [comment]
Assuming this resolved
