### ISSUE TITLE
Insert From Layer

### ISSUE THREAD

**Issue by reixco** [nilsnolde/OSMtools#72]
Hallo GIS enthusiastic,

sorry if my question so basic. how i can input _from layer_ in start location & end location in routing OSM TOOLS.

thanks in advance

**Comment by nilsnolde** [comment]
sorry, this is not a forum. Contact support@openrouteservice.org or our [Google Group.](https://groups.google.com/forum/#!forum/openrouteservice)

And see #47. Make it a single geometry point layer to be safe, not MultiPoint.
